sudo: required
addons:
  hosts:
    - boundless-test
services:
    - docker
env:
  global:
    - PLUGIN_NAME=profiles
  matrix:
  - QGIS_VERSION_TAG=release
  - QGIS_VERSION_TAG=master_2
  - QGIS_VERSION_TAG=master
matrix:
  allow_failures:
  - env: QGIS_VERSION_TAG=master
before_install:
    - docker pull elpaso/qgis-testing-environment:${QGIS_VERSION_TAG}
    - docker tag elpaso/qgis-testing-environment:${QGIS_VERSION_TAG} qgis-testing-environment
install:
    - docker run -d --name qgis-testing-environment -v ${TRAVIS_BUILD_DIR}:/tests_directory -e DISPLAY=:99 qgis-testing-environment
    - sleep 10

    # Setup QGIS to avoid modals and install test auth db
    - docker exec -it qgis-testing-environment sh -c "qgis_setup.sh ${PLUGIN_NAME}"

    # Build the plugin
    - docker exec -it qgis-testing-environment sh -c "pip install paver"
    - docker exec -it qgis-testing-environment sh -c "cd /tests_directory && paver setup"
    - docker exec -it qgis-testing-environment sh -c "ln -s /tests_directory/${PLUGIN_NAME} /root/.qgis2/python/plugins/${PLUGIN_NAME}"

script:
    # Run the unit tests
    - docker exec -it qgis-testing-environment sh -c "qgis_testrunner.sh ${PLUGIN_NAME}.tests.testerplugin.run_tests"
