sudo: required
addons:
  hosts:
  - boundless-test
services:
- docker
env:
  global:
  - PLUGIN_NAME=profiles
  - secure: RRQ96cTFDBkWQG2+FdE77mDgXB/fZc5OZOZTTYcYSugXPncCJWvNEs8chwO2gNp+aF/1Nztbfot6D8dN63nOxLsrg2dKSw+NTtj1HsT1aRDoCoT8uUvbepltnseRWrRTo96i41HSQqU4e7RiDP/3s1keOE049SFItwk0x1ckjNg1LBC40h9Qs5xJaLJn8vQ82AGHQ9VErTMi+hasNhqDdQtiMhSjmdWMrIuPeHFdVUWnCqZ4Jj6gVLqEdreVnl0yhNKSYSuEiJ1Gt6awuYLofZt80EVqsJ4yhdOPO44Njj7CvCn+V75OEZydXuFSPo2B3+WEKc2hnaOf9FmrCBvsToueXmYUjnCv49cRn7BVNHumnbNr5AvcWXIbLzudwo6aM2NazePDUyPolQ3bhJBExwG2RkollrazXtATawT63q72twEEmfI8YpEnWfaN27LLY30bjE0T9t+5QhRGnYFQEY1qiyMjC2I1rKsd39ZdTKDXjl00l3asSyPZz3SkvKyxBzWGHcmQaLaYaeaULXPKkyAZKn/+gd0o/cSWgn4Eo3fGFkb531tsG6PL9iM8Uja9pMuXFlTEWEsinjeQf9PlgaUjetV9C1xc+sbRWQFBeC8W23ye83eYBK9VfQV0+BCRR8lbpyNWoJsDG86tsjtt3/1PXK3OXnjRITsFys22Ykc=
  - secure: GZdnGyGMoAq/yOBuWNZPE4GCup0zZOFMJA2mVxTEhxur50RtIASGs2qjdrTE4TD6pdP4TlMAWJJqiF0nMCLF2Oqo2f6KSZ3Duk1gkp48PeKDd6GhU2TFBo65Okoz6IKdRKS0anvhb8iWTxO4Qws30fYqMbDNRoHCBqyafI9o7o/yeDiUH85n1I7xj1K64nm61lWLIu9t9yR69e3lfTHIEL4YnIIzVmxq+WSVJJl3mfksHIoIuMf9ZB6rE/lYwUqayWCyG+q1M7qtEJ77pglhLJ1wRmje9WVjSDrjJyQMtidgC09c+E48nCNQ55lKri1pnTIa9+npLNDWRYBMmiozwZ1gPEUua2IIZeVEuxCXiD34deruP2z3TMhLCwpxI3zdaMBo1cjLQhL0HHICszivQ3Nt7X5QrKbBmdVpumi+ElS4tVGSz/ERg4JhuaI1V3/Kebqgis8p5Vlu+XULtjX9G/IDSaMntIsF/T6453WCXFwxmiqe4r3Ij4CkTqMxlvq/UcTzKcnjW74EExo12zryWARtuCmrAuXTLM+qZDIKWbc0jocgszyu/gfHfetWF+yrwP8Af/O0RmnexL3QUd8M1sFxI921HryXVhtRlXOQEPpcioCNQppzt+bqHDvKylWmvj6+lyi+1ml8ee6R319WDkd13qbOOgLbfj6rRyfd+NE=
  matrix:
  - QGIS_VERSION_TAG=release
  - QGIS_VERSION_TAG=master_2
  - QGIS_VERSION_TAG=master
matrix:
  allow_failures:
  - env: QGIS_VERSION_TAG=master
before_install:
- docker pull boundlessgeo/qgis-testing-environment:${QGIS_VERSION_TAG}
- docker tag boundlessgeo/qgis-testing-environment:${QGIS_VERSION_TAG} qgis-testing-environment
install:
- docker run -d --name qgis-testing-environment -v ${TRAVIS_BUILD_DIR}:/tests_directory -e DISPLAY=:99 qgis-testing-environment
- sleep 10
- docker exec -it qgis-testing-environment sh -c "qgis_setup.sh ${PLUGIN_NAME}"
- docker exec -it qgis-testing-environment sh -c "pip install paver"
script:
- docker exec -it qgis-testing-environment sh -c "cd /tests_directory && paver setup && paver package --tests"
- docker exec -it qgis-testing-environment sh -c "qgis_testrunner.sh ${PLUGIN_NAME}.tests.testerplugin.run_tests"
notifications:
  slack:
    secure: infcSOCVuOUH8+gUKjel/FIelTtXWSpOoB47oCCaz6zo7EqAkShvEm4fJQB21H64QSi5ohY5Fvc+9sqitZzlC+UP59NwgDNhJZ6Pu9N6hWIQtCodcYSmGmDr/4ykRuk76m/DE270cZyZrsHLfA2RtkxvFEePQWMZx+KWTpcr2nekqimZcN291HpyPHWH/KR7MfPuB2bi2k66f+tvTcjYnFh6tpwJws7/tXiHcP65ezQ3rqUyI+ZQ9FziDPjnFqJNdOcazlIUrn4wRnJ0Y60rYJKBT32QfVgoWD3wEal1xCobkObKu76P1dxJqyV6cv43xUaJyiUwedgUPz46n8gTZt5S+Zw7M9b0xpXtQXNk5LHBKi/9aLgvinVUXWXopoDHxOAmrXENf4Q+ETC5+f95m08UDFzcELS90hR2pzb0PTQOmZqDHMGDuCjMXTh1ASa7BaRQD92P0bzX09RbXfQw1427Cfvn6oLR3lQv+LwVDCoSD0duWyCaAhf2DXvm5s61u6Cd8hPO8+n5FrXKTmdwbZ+4ifwyfGtpruhL7NerGB1urlgpxnuXr1j3uAigzrurt05ItB5IeNzPQh2/wFk7UjHwAWZH/I214XAVDtFonNLd+PKnhzFGT0JnE3BQYxrBHLxQt7IhFFAg68tCR1muRXzRGnD6DZ+FemTrQ8nS97k=
after_success:
- |
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
        mkdir /home/travis/.ssh/
        chmod 700 /home/travis/.ssh/
        openssl aes-256-cbc -K $encrypted_b4f9b335f88a_key -iv $encrypted_b4f9b335f88a_iv -in travis_secrets.tar.gz.enc -out travis_secrets.tar.gz -d
        tar xzvf travis_secrets.tar.gz
        mv id_rsa.qgisrepoguest /home/travis/.ssh/id_rsa.qgisrepoguest
        mv ssh_config /home/travis/.ssh/config
        chmod 600 /home/travis/.ssh/id_rsa.qgisrepoguest
        chmod 600 /home/travis/.ssh/config
        export RELEASE_ZIPNAME=${PLUGIN_NAME}.zip
        echo "Uploading ${RELEASE_ZIPNAME} to QGIS Dev..."
        scp ${PLUGIN_NAME}.zip qgisrepoguest:${UPLOADS}/${RELEASE_ZIPNAME}
        export GIT_REV=$(git rev-parse --short HEAD)
        ssh qgisrepoguest "${UPDATER} update --dev --role desktop-qgis-plugin-dev --git-hash ${GIT_REV} ${RELEASE_ZIPNAME}"
    fi
